parameters:
#    iincoreweb.example.class: IINCORE\webBundle\Example

services:
#    iincoreweb.example:
#        class: %iincoreweb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
